import Options
from os import unlink, symlink, popen
from os.path import exists

srcdir = "."
blddir = "build"
VERSION = "0.0.1"

def set_options(opt):
	opt.tool_options("compiler_cxx")
	
def configure(conf):
	conf.check_tool("compiler_cxx")
	conf.check_tool("node_addon")
	
def build(bld):
	obj = bld.new_task_gen("cxx", "shlib", "node_addon")
	obj.target = "hellosimple"
	obj.source = "hellosimple.cc"
	obj.cxxflags = ["-D_FILE_OFFSET_BITS=64", "-DLARGE_FILE_SOURCE"]
	
def shutdown():
	if Options.commands["clean"]:
		if exists('hellosimple.node'): unlink('hellosimple.node')
	else:
		if exists('build/Release/hellosimple.node') and not exists('hellosimple.node'):
			symlink('build/Release/hellosimple.node', 'hellosimple.node')
